apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fkllmproxy
  labels:
    app: fkllmproxy
spec:
  selector:
    matchLabels:
      app: fkllmproxy
  endpoints:
    - port: http
      path: /metrics/prometheus
      interval: 15s
